### ISSUE TITLE
Hello world not working with latest yew (0.19.3) and latest material-yew (0.2.0)

### ISSUE THREAD

**Issue by Apaksi** [hamza1311/material-yew#32]
Tried to add material-yew's use declarations to my app. Tried both of these because both versions appear in the docs:

`use material_yew::MatButton;`
and
`use material_yew::button::MatButton;`

But both of them give a similar error:

`error[E0432]: unresolved import material_yew::MatButton`

My Cargo.toml looks like this:
```
[package]
name = "test_app"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.19.3"
material-yew = "0.2.0"
```
I'm using `trunk serve` to run the app.

**Comment by hamza1311** [comment]
You need to enable the features, as the README mentions. You can just enable the `full` feature and that should take care of it
